title: Kaboom.pw
description: Kaboom.pw is a multiplayer server for Minecraft that combines free OP with anarchy. Do anything you want, without having to worry about rules.
url: https://kaboom.pw

exclude:
  - build.sh
  - Gemfile
  - LICENSE

sass:
  style: :compressed
