title: Kaboom
description: Kaboom is a multiplayer server for Minecraft that combines free OP with anarchy. Do anything you want, without having to worry about rules.
url: https://kaboom.pw

include:
  - _headers
  - _redirects

exclude:
  - build.sh
  - Gemfile
  - LICENSE

sass:
  style: :compressed
