title: DeluxeMC
description: DeluxeMC is a survival anarchy server.
url: https://deluxemc.net
theme: null

exclude:
  - LICENSE
  - README.md

sass:
  style: :compressed

defaults:
  - scope:
      path: _posts
    values:
      permalink: ""
