title: Flame.ga » Free OP Server
description: Flame.ga provides you a unique experience in Minecraft. On this multiplayer server, you are allowed to do whatever you want.
url: https://flame.ga
exclude:
  - CNAME
  - LICENSE
gems:
  - jekyll-sitemap
