title: Flame.ga » Free OP Server
description: Flame.ga is a Minecraft server where you can do anything you want, whether it be building or testing commands.
url: https://flame.ga
exclude:
  - CNAME
  - LICENSE
gems:
  - jekyll-sitemap
